name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Setup GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
    - name: Install dependencies
      run: sudo pip3 install meson gi-docgen && sudo apt install libgirepository1.0-dev
    - name: Init Meson
      run: make init
    - name: Run build
      run: make all
