name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install gi-docgen meson libgirepository1.0-dev ninja-build clang-14
    - name: Update Alternatives
      run: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 10 && sudo update-alternatives --set clang /usr/bin/clang-14
    - name: Init Meson
      run: make init
    - name: Make docs
      run: make doc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: docs
        folder: build/doc/libtribble-1.0
